### ISSUE TITLE
Bug: inconsistent result between both implementations (go and sh)

### ISSUE THREAD

**Issue by mbideau** [mbideau/btrfs-diff-go#4]
Although
```
Due to BTRFS implementation, some files appear as changed, when they are not (according to diff utility). I have absolutely no idea why BTRFS is acting like this… If someone can help me figures this out, I'll be glad.
```
Makes it hard to use: I redirected the output of both versions into files, and...
```
[mek101@home-server ~/Progetti/go/bin]$ wc -l sh_out go_out 
    33 sh_out
  1723 go_out
```

_Originally posted by @Mek101 in https://github.com/mbideau/btrfs-diff-go/issues/2#issuecomment-913031942_

**Comment by Mek101** [comment]
In regards to that:
./btrfs-diff-go --debug /mountpoints/raid1/anime/data_snapshot.20210816/ /mountpoints/raid1/anime/bk_data_snapshot.2021094/
All debug outputs are a variant of this

[DEBUG] Cmd [15 0 54 0 49 49 101 121 101 115 47 91 102 114 111 122 101 110 100 97 108 101 93 49 49 95 101 121 101 115 95 48 49 95 91 120 118 105 100 95 105 116 97 93 91 53 56 49 100 52 52 55 102 93 46 97 118 105 11 0 12 0 241 74 30 97 0 0 0 0 160 65 202 43 10 0 12 0 144 150 206 95 0 0 0 0 154 157 48 44 9 0 12 0 109 53 191 96 0 0 0 0 131 75 240 22]; type BTRFS_SEND_C_UTIMES
[DEBUG] TRACE       BTRFS_SEND_C_UTIMES 11eyes/[frozendale]11_eyes_01_[xvid_ita][581d447f].avi
[DEBUG] TRACE    changed 11eyes/[frozendale]11_eyes_01_[xvid_ita][581d447f].avi
[DEBUG] peekAndDiscard() need to read more bytes '4' than there are buffered '0'
[DEBUG] peekAndDiscard() increasing the buffer size to match the need

And with ./btrfs-diff-go --debug /mountpoints/raid1/anime/data_snapshot.20210816/ /mountpoints/raid1/anime/bk_data_snapshot.2021094/ 2>1 | grep " BTRFS_SEND_"

Only false positives appear in the output

Originally posted by @Mek101 in https://github.com/mbideau/btrfs-diff-go/issues/2#issuecomment-913033735

***

Could it be that the detected change was the access time? I wasn't able to find any information regarding `BTRFS_SEND_C_UTIMES`, however, "utime" and similar variants seem to always refer to changing the access and modification times. If that is the case, then it should suffice to explicitly ignore the command in https://github.com/mbideau/btrfs-diff-go/blob/64d98c9f2fdce098fd7966e6454edd0950b2fc8b/pkg/btrfs-diff.go#L121
- https://man7.org/linux/man-pages/man2/utime.2.html
- https://code.woboq.org/linux/linux/fs/utimes.c.html

**Comment by mbideau** [comment]
"utimes" should already be ignored, but I'll dig more into it ...

**Comment by mbideau** [comment]
Hey @Mek101,
I have added multiple options, and removed a lot of 'changed' by default (see dbfde36, 1c67135, 25f46f8, bab5ebd).
See the new _README_ usage section.

Can you update your code, and try again with your data above ?

Thank you in advance :wink:

**Comment by Mek101** [comment]
I confirm the fix👍

**Comment by mbideau** [comment]
For your information, I have found more inconsistencies between the two (minor stuff), and I have done a massive rewrite to fix the other bug in the go version.
I still need to properly commit all that, and it's gonna be good, for both programs I think (I am already testing one against the other).

Anyway, thank you again for you feedback :wink:

**Comment by mbideau** [comment]
Hey @Mek101,
I have resolved all the inconsistencies between the Go version and the Shell one. Turned out that there were multiple ones, on both side, despite the test scripts that passes successfully for both.
Now both version are producing the same output, which is conform to the one of the standard _GNU diff_ (if it were used to really do a diff between the subvolumes).
You can check it out again if you want ... that would be great :smiley:
